service:
  name: utopiafinder

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  graphql:
    handler: src/graphql/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
